sudo: required
services:
  - docker
before_install:
  - docker build -t guugli/reacttesto -f ./client/Dockerfile.dev ./client
secript:
  - docker run -e CI=true guugli/reacttesto npm run test -- --coverage
after_success:
  - docker build -t guugli/clienttesto ./client
  - docker build -t guugli/nginxtesto ./nginx
  - docker build -t guugli/servertesto ./server
  - docker build -t guugli/workertesto ./worker
  - echo "$DOCKER_PASS" | docker login -u "DOCKER_ID" --password-stdin
  - docker push guugli/clienttesto
  - docker push guugli/nginxtessto
  - docker push guugli/servertesto
  - docker push guugli/workertesto